server:
  port: 8012   #port number
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: scheduler   
     
management:
  security:
    enabled: false  
 
logging:
  level:
    com.du.gateway.eurekagateway: DEBUG